"""Frontend code generator — generates Flutter application code."""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

from app.generators.base_generator import BaseGenerator

logger = logging.getLogger(__name__)


class FrontendGenerator(BaseGenerator):
    """Generates Flutter frontend code from an architectural plan."""

    def generate_project_structure(self, app_name: str = "my_app") -> list[Path]:
        """Generate the basic Flutter project structure."""
        created = []

        # pubspec.yaml
        created.append(self.write_file("frontend/pubspec.yaml", self._get_pubspec(app_name)))

        # Main entry
        created.append(self.write_file("frontend/lib/main.dart", self._get_main_dart(app_name)))
        created.append(self.write_file("frontend/lib/app.dart", self._get_app_dart()))

        # Core
        created.append(self.write_file("frontend/lib/core/config/app_config.dart", self._get_config_dart()))
        created.append(self.write_file("frontend/lib/core/theme/app_theme.dart", self._get_theme_dart()))
        created.append(self.write_file("frontend/lib/core/api/api_client.dart", self._get_api_client_dart()))
        created.append(self.write_file("frontend/lib/core/router/app_router.dart", self._get_router_dart()))

        # Features
        created.append(self.write_file("frontend/lib/features/auth/login_screen.dart", self._get_login_screen()))
        created.append(self.write_file("frontend/lib/features/home/home_screen.dart", self._get_home_screen()))

        # Web
        created.append(self.write_file("frontend/web/index.html", self._get_web_html(app_name)))

        logger.info(f"Generated frontend structure: {len(created)} files")
        return created

    def _get_pubspec(self, app_name: str) -> str:
        return f"""name: {app_name}
description: Generated by Apex Studio
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.0.0
  flutter_riverpod: ^2.5.0
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
"""

    def _get_main_dart(self, app_name: str) -> str:
        return f"""import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'app.dart';

void main() {{
  runApp(const ProviderScope(child: {app_name.capitalize()}App()));
}}
"""

    def _get_app_dart(self) -> str:
        return """import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'core/router/app_router.dart';
import 'core/theme/app_theme.dart';

class MyAppApp extends ConsumerWidget {
  const MyAppApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(appRouterProvider);
    return MaterialApp.router(
      title: 'My App',
      theme: AppTheme.light,
      darkTheme: AppTheme.dark,
      routerConfig: router,
      debugShowCheckedModeBanner: false,
    );
  }
}
"""

    def _get_config_dart(self) -> str:
        return """class AppConfig {
  static const String apiUrl = String.fromEnvironment(
    'API_URL',
    defaultValue: 'http://localhost:8000',
  );
  static const String appName = String.fromEnvironment(
    'APP_NAME',
    defaultValue: 'My App',
  );
}
"""

    def _get_theme_dart(self) -> str:
        return """import 'package:flutter/material.dart';

class AppTheme {
  static ThemeData get light => ThemeData(
    useMaterial3: true,
    colorSchemeSeed: Colors.blue,
    brightness: Brightness.light,
  );

  static ThemeData get dark => ThemeData(
    useMaterial3: true,
    colorSchemeSeed: Colors.blue,
    brightness: Brightness.dark,
  );
}
"""

    def _get_api_client_dart(self) -> str:
        return """import 'package:dio/dio.dart';
import '../config/app_config.dart';

class ApiClient {
  late final Dio _dio;

  ApiClient() {
    _dio = Dio(BaseOptions(
      baseUrl: AppConfig.apiUrl,
      connectTimeout: const Duration(seconds: 30),
      receiveTimeout: const Duration(seconds: 30),
      headers: {'Content-Type': 'application/json'},
    ));
  }

  Future<Response> get(String path, {Map<String, dynamic>? params}) =>
      _dio.get(path, queryParameters: params);

  Future<Response> post(String path, {dynamic data}) =>
      _dio.post(path, data: data);

  Future<Response> put(String path, {dynamic data}) =>
      _dio.put(path, data: data);

  Future<Response> delete(String path) => _dio.delete(path);

  void setToken(String token) {
    _dio.options.headers['Authorization'] = 'Bearer $token';
  }

  void clearToken() {
    _dio.options.headers.remove('Authorization');
  }
}
"""

    def _get_router_dart(self) -> str:
        return """import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../features/home/home_screen.dart';
import '../features/auth/login_screen.dart';

final appRouterProvider = Provider<GoRouter>((ref) {
  return GoRouter(
    initialLocation: '/',
    routes: [
      GoRoute(path: '/', builder: (_, __) => const HomeScreen()),
      GoRoute(path: '/login', builder: (_, __) => const LoginScreen()),
    ],
  );
});
"""

    def _get_login_screen(self) -> str:
        return """import 'package:flutter/material.dart';

class LoginScreen extends StatefulWidget {
  const LoginScreen({super.key});

  @override
  State<LoginScreen> createState() => _LoginScreenState();
}

class _LoginScreenState extends State<LoginScreen> {
  final _emailController = TextEditingController();
  final _passwordController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Login')),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          children: [
            TextField(
              controller: _emailController,
              decoration: const InputDecoration(labelText: 'Email'),
            ),
            const SizedBox(height: 16),
            TextField(
              controller: _passwordController,
              decoration: const InputDecoration(labelText: 'Password'),
              obscureText: true,
            ),
            const SizedBox(height: 24),
            ElevatedButton(
              onPressed: () {},
              child: const Text('Login'),
            ),
          ],
        ),
      ),
    );
  }
}
"""

    def _get_home_screen(self) -> str:
        return """import 'package:flutter/material.dart';

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Home')),
      body: const Center(
        child: Text('Welcome!'),
      ),
    );
  }
}
"""

    def _get_web_html(self, app_name: str) -> str:
        return """<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>$app_name</title>
  <link rel="manifest" href="manifest.json">
</head>
<body>
  <script src="main.dart.js" type="application/javascript"></script>
</body>
</html>
"""
